
find_path(ALLEGRO5_INCLUDE_DIR
	NAMES allegro.h
	PATH_SUFFIXES allegro5
)

find_library(ALLEGRO5_LIBRARY
	NAMES allegro
)

find_library(ALLEGRO5_DIALOG_LIBRARY NAMES allegro_dialog)
find_library(ALLEGRO5_IMAGE_LIBRARY NAMES allegro_image)
find_library(ALLEGRO5_PRIMITIVES_LIBRARY NAMES allegro_primitives)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
	Allegro5 FOUND_VAR ALLEGRO5_FOUND
	REQUIRED_VARS ALLEGRO5_INCLUDE_DIR ALLEGRO5_LIBRARY
	ALLEGRO5_DIALOG_LIBRARY ALLEGRO5_IMAGE_LIBRARY ALLEGRO5_PRIMITIVES_LIBRARY
)

mark_as_advanced(
	ALLEGRO5_INCLUDE_DIR
	ALLEGRO5_LIBRARY
	ALLEGRO5_DIALOG_LIBRARY
	ALLEGRO5_IMAGE_LIBRARY
	ALLEGRO5_PRIMITIVES_LIBRARY
)
